version: 2


models:
  - name: stg_btc
    columns:
      - name: HASHKEY
        tests:
          - unique
          - not_null
  
  - name: stg_btc_outputs
    tests:
      - dbt_utils.equal_rowcount:
          compare_model: ref('stg_btc_outputs_py')

  - name: whale_alert
    columns:
      - name: output_address
        data_tests:
          - assert_valid_btc_address

#To expose to create dashboards using locker studio
exposures:

  - name: btc_whale_alert_exposure
    label: BTC Whale alert
    type: dashboard
    maturity: high
    url: https://lookerstudio.google.com/reporting/replace_with_your_own_looker_report
    description: >
      BTC Whale alert transactions report"?

    depends_on:
      - ref('whale_alert')

    owner:
      name: Allan Vargas
